# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/*_schema.rb"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
